export interface IMockPetition {
    id: number,
    label: string,
    number: number,
    dateCreate: string,
    dateChange: string,
    dateWrong: string,
    status: "В работе" | "Зарегистрировано" | "На согласовании" | "Выполнено. Требует подтверждения" | "Закрыто",
    description: string,
    result: string,
    service: string,
    comService: string,
    waiting: boolean
}

export const petitions: IMockPetition[] = [
    {
        id: 1,
        label: "Электронная почта",
        number: 1,
        dateCreate: "20.05.2020 15:22",
        dateChange: "20.05.2020 15:22",
        dateWrong: "20.05.2020 15:22",
        status: "В работе",
        description: "Это описание проекта",
        result: "Результат",
        service: "Услуга",
        comService: "Состав услуги",
        waiting: false
    },
    {
        id: 2,
        label: "Установка платформы 1С",
        number: 2,
        dateCreate: "20.05.2020 15:22",
        dateChange: "20.05.2020 15:22",
        dateWrong: "20.05.2020 15:22",
        status: "Зарегистрировано",
        description: "Это описание проекта",
        result: "Результат",
        service: "Услуга",
        comService: "Состав услуги",
        waiting: false
    },
    {
        id: 3,
        label: "Подключение к корпоративной сети",
        number: 3,
        dateCreate: "20.05.2020 15:22",
        dateChange: "20.05.2020 15:22",
        dateWrong: "20.05.2020 15:22",
        status: "На согласовании",
        description: "Это описание проекта",
        result: "Результат",
        service: "Услуга",
        comService: "Состав услуги",
        waiting: false
    },
    {
        id: 4,
        label: "Установка ПО на ПК",
        number: 4,
        dateCreate: "20.05.2020 15:22",
        dateChange: "20.05.2020 15:22",
        dateWrong: "20.05.2020 15:22",
        status: "Выполнено. Требует подтверждения",
        description: "Это описание проекта",
        result: "Результат",
        service: "Услуга",
        comService: "Состав услуги",
        waiting: true
    },
    {
        id: 5,
        label: "Проблема с сетью",
        number: 5,
        dateCreate: "20.05.2020 15:22",
        dateChange: "20.05.2020 15:22",
        dateWrong: "20.05.2020 15:22",
        status: "Закрыто",
        description: "Это описание проекта",
        result: "Результат",
        service: "Услуга",
        comService: "Состав услуги",
        waiting: false
    },
    {
        id: 6,
        label: "Электронная почта",
        number: 6,
        dateCreate: "20.05.2020 15:22",
        dateChange: "20.05.2020 15:22",
        dateWrong: "20.05.2020 15:22",
        status: "В работе",
        description: "Это описание проекта",
        result: "Результат",
        service: "Услуга",
        comService: "Состав услуги",
        waiting: true
    },
    {
        id: 7,
        label: "Установка платформы 1С",
        number: 7,
        dateCreate: "20.05.2020 15:22",
        dateChange: "20.05.2020 15:22",
        dateWrong: "20.05.2020 15:22",
        status: "Зарегистрировано",
        description: "Это описание проекта",
        result: "Результат",
        service: "Услуга",
        comService: "Состав услуги",
        waiting: false
    },
    {
        id: 8,
        label: "Подключение к корпоративной сети",
        number: 8,
        dateCreate: "20.05.2020 15:22",
        dateChange: "20.05.2020 15:22",
        dateWrong: "20.05.2020 15:22",
        status: "На согласовании",
        description: "Это описание проекта",
        result: "Результат",
        service: "Услуга",
        comService: "Состав услуги",
        waiting: false
    },
    {
        id: 9,
        label: "Установка ПО на ПК",
        number: 9,
        dateCreate: "20.05.2020 15:22",
        dateChange: "20.05.2020 15:22",
        dateWrong: "20.05.2020 15:22",
        status: "Выполнено. Требует подтверждения",
        description: "Это описание проекта",
        result: "Результат",
        service: "Услуга",
        comService: "Состав услуги",
        waiting: false
    },
    {
        id: 10,
        label: "Проблема с сетью",
        number: 10,
        dateCreate: "20.05.2020 15:22",
        dateChange: "20.05.2020 15:22",
        dateWrong: "20.05.2020 15:22",
        status: "Закрыто",
        description: "Это описание проекта",
        result: "Результат",
        service: "Услуга",
        comService: "Состав услуги",
        waiting: false
    },
];
